name: React CI/CD with Port 80

on:
  push:
    branches: [ main ]

jobs:
  deploy-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Upload React App to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: "~/highteenday-front-server"

      - name: Install & Start React App on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 디렉토리가 없으면 생성
            mkdir -p ~/highteenday-front-server
            cd ~/highteenday-front-server

            # 의존성 설치 (peerDeps 오류 방지)
            npm install --legacy-peer-deps

            # PM2로 실행
            pm2 delete react-app || true
            pm2 start npm --name "react-app" -- run start
            pm2 save
