name: React CI/CD with Port 80

on:
  push:
    branches: [ main ]

jobs:
  deploy-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Remove old app directory before upload
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf ~/highteenday-front-server
            sudo rm -rf /home/ubuntu/front-end

      - name: Upload React App to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: "~/highteenday-front-server"
          rm: false
          overwrite: true
          strip_components: 0
          # exclude: ".git" #

      - name: Install & Start React App on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/highteenday-front-server
            cd ~/highteenday-front-server

            # 의존성 설치
            npm install --legacy-peer-deps

            # 빌드 파일 생성
            npm run build
            
            # nginx 폴더로 서빙
            cp -r ~/highteenday-front-server/build/ /home/ubuntu/front-end

            # 권한 주기 
            sudo chmod o+x /home/ubuntu
            sudo chmod -R o+rx /home/ubuntu/front-end

            # nginx 재시작
            sudo systemctl restart nginx