name: React Build & Deploy to Ubuntu Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies and Build React App
        run: |
          npm install --legacy-peer-deps
          CI=false npm run build

      - name: Compress build folder
        run: zip -r build.zip build

      - name: Remove existing front-end folder on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASP_HOST }}
          username: ${{ secrets.RASP_USER }}
          key: ${{ secrets.RASP_SSH_KEY }}
          port: ${{ secrets.RASP_PORT }}
          script: |
            sudo rm -rf /home/rasp-user/front-end

      - name: Upload build.zip to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.RASP_HOST }}
          username: ${{ secrets.RASP_USER }}
          key: ${{ secrets.RASP_SSH_KEY }}
          port: ${{ secrets.RASP_PORT }}
          source: "build.zip"
          target: "/home/rasp-user"

      - name: Unzip and move to front-end directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASP_HOST }}
          username: ${{ secrets.RASP_USER }}
          key: ${{ secrets.RASP_SSH_KEY }}
          port: ${{ secrets.RASP_PORT }}
          script: |
            unzip -o /home/rasp-user/build.zip -d /home/rasp-user/
            mv /home/rasp-user/build /home/rasp-user/front-end
            rm /home/rasp-user/build.zip

            sudo chmod o+x /home/rasp-user
            sudo chmod -R o+rx /home/rasp-user/front-end

            sudo systemctl restart nginx
